import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import Card from '../components/card'
import styles from '../styles/Home.module.css'
import {fetchCoffeeStores} from '../lib/coffee-stores'

export async function getStaticProps() {

  let coffeeStoresData = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores: coffeeStoresData,
    }
  }
}

export default function Home(props) {

  const handleOnBtnClick = () => {
    console.log("Hello, World");
  }

  return (

    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner btnText="View stores Nearby" handleOnClick={handleOnBtnClick} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        {props.coffeeStores.length > 1 && 
        <>
          <h2 className={styles.heading2}>Delhi Stores</h2>
          <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore) => {
            return (
              
              <Card 
              key={coffeeStore.id}
              name={coffeeStore.name} 
              imgUrl={coffeeStore.imgUrl || 'https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80'} 
              href={`/coffee-store/${coffeeStore.id}`} />
            )
          })}
          </div>
        </>}
      </main>
    </div>
  )
}
